# Generated by Django 6.1.1 on 2026-09-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faults', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faultreport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='fault_images/'),
        ),
    ]
