# Generated by Django 6.1.1 on 2026-09-24 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faults', '0002_faultreport_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='faultreport',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
