# Generated by Django 6.1.1 on 2026-09-16 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('condition', models.CharField(choices=[('OPERATIONAL', 'Operational'), ('UNDER_MAINTENANCE', 'Under Maintenance'), ('FAULTY', 'Faulty'), ('DECOMMISSIONED', 'Decommissioned')], default='OPERATIONAL', max_length=30)),
                ('installed_date', models.DateField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='locations.location')),
            ],
        ),
    ]
