# Generated by Django 6.1.1 on 2026-09-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='installed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
