# Generated by Django 6.1.1 on 2026-09-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_alter_equipment_installed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='location',
            field=models.CharField(max_length=200),
        ),
    ]
